// firebase

Object {
  "INTERNAL": Object {
    "ErrorFactory": [Function ErrorFactory],
    "components": Map {
      "platform-logger" => Component {
        "instanceFactory": [Function anonymous],
        "instantiationMode": "LAZY",
        "multipleInstances": false,
        "name": "platform-logger",
        "onInstanceCreated": null,
        "serviceProps": Object {},
        "type": "PRIVATE",
      },
      "fire-core-rn-version" => Component {
        "instanceFactory": [Function anonymous],
        "instantiationMode": "LAZY",
        "multipleInstances": false,
        "name": "fire-core-rn-version",
        "onInstanceCreated": null,
        "serviceProps": Object {},
        "type": "VERSION",
      },
      "fire-js-version" => Component {
        "instanceFactory": [Function anonymous],
        "instantiationMode": "LAZY",
        "multipleInstances": false,
        "name": "fire-js-version",
        "onInstanceCreated": null,
        "serviceProps": Object {},
        "type": "VERSION",
      },
      "auth" => Object {
        "instanceFactory": [Function instanceFactory],
        "instantiationMode": "LAZY",
        "multipleInstances": false,
        "name": "auth",
        "onInstanceCreated": [Function onInstanceCreated],
        "serviceProps": Object {
          "ActionCodeInfo": Object {
            "Operation": Object {
              "EMAIL_SIGNIN": "EMAIL_SIGNIN",
              "PASSWORD_RESET": "PASSWORD_RESET",
              "RECOVER_EMAIL": "RECOVER_EMAIL",
              "REVERT_SECOND_FACTOR_ADDITION": "REVERT_SECOND_FACTOR_ADDITION",
              "VERIFY_AND_CHANGE_EMAIL": "VERIFY_AND_CHANGE_EMAIL",
              "VERIFY_EMAIL": "VERIFY_EMAIL",
            },
          },
          "ActionCodeURL": [Function d],
          "Auth": [Function Fn],
          "AuthCredential": [Function Bg],
          "EmailAuthProvider": [Function d],
          "Error": [Function t],
          "FacebookAuthProvider": [Function d],
          "GithubAuthProvider": [Function d],
          "GoogleAuthProvider": [Function d],
          "OAuthProvider": [Function d],
          "PhoneAuthProvider": [Function d],
          "PhoneMultiFactorGenerator": [Function d],
          "RecaptchaVerifier": [Function d],
          "SAMLAuthProvider": [Function d],
          "TwitterAuthProvider": [Function d],
        },
        "type": "PUBLIC",
      },
      "auth-internal" => Object {
        "instanceFactory": [Function instanceFactory],
        "instantiationMode": "LAZY",
        "multipleInstances": false,
        "name": "auth-internal",
        "type": "PRIVATE",
      },
      "fire-auth-version" => Component {
        "instanceFactory": [Function anonymous],
        "instantiationMode": "LAZY",
        "multipleInstances": false,
        "name": "fire-auth-version",
        "onInstanceCreated": null,
        "serviceProps": Object {},
        "type": "VERSION",
      },
      "database" => Component {
        "instanceFactory": [Function anonymous],
        "instantiationMode": "LAZY",
        "multipleInstances": true,
        "name": "database",
        "onInstanceCreated": null,
        "serviceProps": Object {
          "DataSnapshot": [Function DataSnapshot],
          "Database": [Function Database],
          "INTERNAL": Object {
            "dataUpdateCount": [Function dataUpdateCount],
            "forceLongPolling": [Function forceLongPolling],
            "forceWebSockets": [Function forceWebSockets],
            "initStandalone": [Function initStandalone],
            "interceptServerData": [Function interceptServerData],
            "isWebSocketsAvailable": [Function isWebSocketsAvailable],
            "setSecurityDebugCallback": [Function setSecurityDebugCallback],
            "stats": [Function stats],
            "statsIncrementCounter": [Function statsIncrementCounter],
          },
          "Query": [Function Query],
          "Reference": [Function Reference],
          "ServerValue": Object {
            "TIMESTAMP": Object {
              ".sv": "timestamp",
            },
            "increment": [Function increment],
          },
          "TEST_ACCESS": Object {
            "ConnectionTarget": [Function RepoInfo],
            "DataConnection": [Function PersistentConnection],
            "RealTimeConnection": [Function Connection],
            "forceRestClient": [Function forceRestClient],
            "hijackHash": [Function hijackHash],
            "queryIdentifier": [Function queryIdentifier],
          },
          "enableLogging": [Function enableLogging],
        },
        "type": "PUBLIC",
      },
      "fire-rtdb-version" => Component {
        "instanceFactory": [Function anonymous],
        "instantiationMode": "LAZY",
        "multipleInstances": false,
        "name": "fire-rtdb-version",
        "onInstanceCreated": null,
        "serviceProps": Object {},
        "type": "VERSION",
      },
      "storage" => Component {
        "instanceFactory": [Function factory],
        "instantiationMode": "LAZY",
        "multipleInstances": true,
        "name": "storage",
        "onInstanceCreated": null,
        "serviceProps": Object {
          "Reference": [Function ReferenceCompat],
          "Storage": [Function FirebaseStorageImpl],
          "StringFormat": Object {
            "BASE64": "base64",
            "BASE64URL": "base64url",
            "DATA_URL": "data_url",
            "RAW": "raw",
          },
          "TaskEvent": Object {
            "STATE_CHANGED": "state_changed",
          },
          "TaskState": Object {
            "CANCELED": "canceled",
            "ERROR": "error",
            "PAUSED": "paused",
            "RUNNING": "running",
            "SUCCESS": "success",
          },
        },
        "type": "PUBLIC",
      },
      "fire-gcs-version" => Component {
        "instanceFactory": [Function anonymous],
        "instantiationMode": "LAZY",
        "multipleInstances": false,
        "name": "fire-gcs-version",
        "onInstanceCreated": null,
        "serviceProps": Object {},
        "type": "VERSION",
      },
      "firestore" => Component {
        "instanceFactory": [Function anonymous],
        "instantiationMode": "LAZY",
        "multipleInstances": false,
        "name": "firestore",
        "onInstanceCreated": null,
        "serviceProps": Object {
          "Blob": [Function La],
          "CACHE_SIZE_UNLIMITED": -1,
          "CollectionReference": [Function ih],
          "DocumentReference": [Function Ha],
          "DocumentSnapshot": [Function Za],
          "FieldPath": [Function oh],
          "FieldValue": [Function ch],
          "Firestore": [Function Ka],
          "GeoPoint": [Function xu],
          "Query": [Function eh],
          "QueryDocumentSnapshot": [Function th],
          "QuerySnapshot": [Function sh],
          "Timestamp": [Function L],
          "Transaction": [Function Wa],
          "WriteBatch": [Function Ga],
          "setLogLevel": [Function ja],
        },
        "type": "PUBLIC",
      },
      "fire-fst-version" => Component {
        "instanceFactory": [Function anonymous],
        "instantiationMode": "LAZY",
        "multipleInstances": false,
        "name": "fire-fst-version",
        "onInstanceCreated": null,
        "serviceProps": Object {},
        "type": "VERSION",
      },
      "firebase-app-version" => Component {
        "instanceFactory": [Function anonymous],
        "instantiationMode": "LAZY",
        "multipleInstances": false,
        "name": "firebase-app-version",
        "onInstanceCreated": null,
        "serviceProps": Object {},
        "type": "VERSION",
      },
      "firebase-rn-version" => Component {
        "instanceFactory": [Function anonymous],
        "instantiationMode": "LAZY",
        "multipleInstances": false,
        "name": "firebase-rn-version",
        "onInstanceCreated": null,
        "serviceProps": Object {},
        "type": "VERSION",
      },
    },
    "createFirebaseNamespace": [Function createFirebaseNamespace],
    "createSubscribe": [Function createSubscribe],
    "deepExtend": [Function deepExtend],
    "extendNamespace": [Function extendNamespace],
    "reactNative": Object {
      "AsyncStorage": Object {
        "_getKeys": Array [],
        "_getRequests": Array [],
        "_immediate": null,
        "clear": [Function clear],
        "flushGetRequests": [Function flushGetRequests],
        "getAllKeys": [Function getAllKeys],
        "getItem": [Function getItem],
        "mergeItem": [Function mergeItem],
        "multiGet": [Function multiGet],
        "multiMerge": [Function multiMerge],
        "multiRemove": [Function multiRemove],
        "multiSet": [Function multiSet],
        "removeItem": [Function removeItem],
        "setItem": [Function setItem],
      },
    },
    "registerComponent": [Function registerComponent],
    "removeApp": [Function removeApp],
    "useAsService": [Function useAsService],
  },
  "SDK_VERSION": "8.10.0",
  "User": [Function Im],
  "__esModule": true,
  "app": [Function app],
  "apps": Array [
    Object {
      "automaticDataCollectionEnabled": false,
      "name": "[DEFAULT]",
      "options": Object {
        "apiKey": "AIzaSyA_qQtW0Nw1IHa7IaBTZ_sy11W-R0tYMbI",
        "appId": "1:35800927884:web:443bafcccad4f20d8875a9",
        "authDomain": "memoapp-c7a87.firebaseapp.com",
        "messagingSenderId": "35800927884",
        "projectId": "memoapp-c7a87",
        "storageBucket": "memoapp-c7a87.appspot.com",
      },
    },
  ],
  "auth": [Function serviceNamespace],
  "database": [Function serviceNamespace],
  "default": [Circular],
  "firestore": [Function serviceNamespace],
  "initializeApp": [Function initializeApp],
  "onLog": [Function onLog],
  "registerVersion": [Function registerVersion],
  "setLogLevel": [Function setLogLevel],
  "storage": [Function serviceNamespace],
}

